name: Update README Index

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-index:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT_TOKEN }}

      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/${{ github.repository }}.git

      - name: Update README index
        run: |
          # your script to update README goes here
          echo "Updating README index..."

      - name: Commit and Push changes
        run: |
          git add README.md || true
          git diff --staged --quiet || (git commit -m "chore(docs): update README index [skip ci]" && git push)
