name: Update Projects Index and README

on:
  push:
    branches:
      - main
    paths:
      - 'projects/**'
      - 'scripts/generate_and_inject.py'
      - 'README.md'
      - '!PROJECTS_INDEX.md'

jobs:
  update-index:
    # جلوگیری از اجرا در commitهایی که از workflow انجام شده‌اند:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies (if any)
        run: python -m pip install --upgrade pip

      - name: Generate PROJECTS_INDEX.md
        run: python3 scripts/generate_and_inject.py --root projects --output PROJECTS_INDEX.md

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add PROJECTS_INDEX.md README.md || true
          git diff --staged --quiet || (git commit -m "chore(docs): update PROJECTS_INDEX and README [skip ci]" && git push)
